### PR TITLE
Split SG6 By Rings + Goals

### LINKED ISSUE #148: Split <SG6> into A and B Bullets
Feedback from Head Referee:

> SG6 needs to be broken up into SG6.a and SG6.b

> Adding “ring” or “goal” to notes isn’t too hard, but would be nice to just click on one and know which specific violation it is at a glance. It is helpful when reviewing violations with the kids, too, so I don’t have to pull up each violation to confirm if it was a ring or goal when it has been entered by another ref.

### PR DESCRIPTION
**Pull request by MiniMitre**
## Overview
This fixes #148, but does require some carfeul consideration before merging.

## The Initial Problem
Implementing the fix as stated in the issue: `SG6 needs to be broken up into SG6.a and SG6.b` had the problem where it is not obvious if `a` meant rings or goals. So I thought it was necessary to write `<SG6 - Goals>` and `<SG6 - Rings>` as seperate 'rules' in the `2024-2025.json`

### SideNote
I do not believe we are using `rules.json` anywhere anymore, so it has been removed for clarity

## The Problem with that solution
I found that it was anonying to have to read 'rings' and 'goals' everytime I went to click on an SG6 violation, so I added icons for a ring and a goal, which makes it clear much quicker what we are referring to.

## Question
Is there a way for us to 'remove' <SG6> from the `Associated Rules`, because even if it is not a rule in the list (which it won't be after we make this change), I think it will still appear as an associated rule if anyone has used it before, and it can still be selected and used in future incidents, potentially leading to 3 types of SG6 violations

### CODE REVIEW

File: src/utils/hooks/rules.ts [hunk 1]
```diff
@@ -7,6 +7,7 @@ export type Rule = {
   rule: string;
   description: string;
   link: string;
+  icon?: string;
```
Comment (MiniMitre) [inline src/utils/hooks/rules.ts:10]: Icon added as an optional parameter, so we can add icons to other rules as well if we want to

File: src/components/Incident.tsx [hunk 2]
```diff
@@ -60,8 +94,10 @@ export const Incident: React.FC<IncidentProps> = ({
           props.className
         )}
       >
-        <div className="flex-1 overflow-clip">
-          <p className="text-sm whitespace-nowrap">{highlights.join(" • ")}</p>
+        <div className="flex-1 overflow-x-auto">
+          <div className="text-sm whitespace-nowrap">
+            <div className="flex items-center gap-x-3">{highlights}</div>
```
Comment (MiniMitre) [inline src/components/Incident.tsx:99]: Allows us to have images as well as text in the 'highlights'

Does remove the bullet point but we can always add that back if you think it is needed

File: src/components/Incident.tsx [hunk 3]
```diff
@@ -28,21 +30,53 @@ export const Incident: React.FC<IncidentProps> = ({
...
+
+          return [];
+        })
+        .find(Boolean); // Find the first valid icon and stop at that point
+
+      if (icon) {
+        base.push(<span>{icon}</span>);
+      }
+
+      base.push(<span>{rule}</span>);
```
Comment (MiniMitre) [inline src/components/Incident.tsx:71]: After adding the ability to scroll across incidents to find overflow, I think it makes more sense to list ALL of the incidents one after another

File: src/utils/hooks/rules.ts (hunk 1 above)
Comment (brenapp) [reply src/utils/hooks/rules.ts:10]: Please add this to the JSON schema in `public/rules/schema.json`

File: src/components/Incident.tsx [hunk 4]
```diff
@@ -60,8 +94,10 @@ export const Incident: React.FC<IncidentProps> = ({
           props.className
         )}
       >
-        <div className="flex-1 overflow-clip">
-          <p className="text-sm whitespace-nowrap">{highlights.join(" • ")}</p>
+        <div className="flex-1 overflow-x-auto">
```
Comment (MiniMitre) [inline src/components/Incident.tsx:97]: Overflow-clip caused some problems on small screen sizes where the 'edit incident' button was no longer visible (even without listing all of the incidents and using the +1/+ 2 thing. So allow the user to swipe across to read the entire incident info

**Review by MiniMitre — COMMENTED** [review]
Comments for Brendan's review

File: src/components/Incident.tsx (hunk 4 above)
Comment (brenapp) [reply src/components/Incident.tsx:96]: However, I am unsure of the correct approach for overflow in the x direction. If possible, I aim to keep things in a single view and minimize the number of scrollbars on the view. The point of the incident component here is mostly to be a reminder of the violation for the end user. If they want to get more information (like the contents of the description beyond the first line), they would need to open it up in edit mode anyway.

Maybe for us to decide together here, is it even worth displaying multiple rules if there is more than one incident? In my experience, end users typically create multiple incidents for discrete violations, so the number of end users that would even see multiple violations is very low.

File: public/rules/V5RC/2024-2025.json [hunk 5]
```diff
@@ -34,9 +34,16 @@
           "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/SG5.html"
         },
         {
-          "rule": "<SG6>",
-          "description": "Possession is limited to two Rings and one Mobile Goal",
-          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/SG6.html"
+          "rule": "<SG6 - Rings>",
+          "description": "Possession is limited to two Rings",
+          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/SG6.html",
+          "icon": "/icons/High_Stakes_Ring.png"
```
Comment (brenapp) [inline public/rules/V5RC/2024-2025.json:40]: We should move these icons to a game-specific subfolder of assets, like 

```
icons/2024-2025/V5RC/goal.png
```

**Review by brenapp — CHANGES_REQUESTED** [review]
Looks good! I like the icon change, but I have some suggestions for implementing it.

File: public/rules/V5RC/2024-2025.json [hunk 6]
```diff
@@ -34,9 +34,16 @@
...
+        },
```
[the remark this answers is not in the document]
Comment (MiniMitre) [reply public/rules/V5RC/2024-2025.json:41]: Now I think about it, because we can have the icons next to the 'associated rules' I think R and G are better than 'Rings' and 'Goals'.

In some situations the icons are not visible, e.g. the selct menu (Cannot have div as child of option), however in those cases either the description is available or the potential ambiguity shouldn't be too bad

File: src/components/Incident.tsx (hunk 4 above)
Comment (MiniMitre) [reply src/components/Incident.tsx:96]: I agree overflow is not the right way to deal with this. I think some kind of shorthand for 'multiple violations' is better than <SG6> + 1 (because the rule chosen to be displayed is not necessarily the most important rule). Do you have any ideas what that could be.

Also a possible feature add would be a 'view' icon next to or instead of the 'edit' button. Just to stop people accidentally editing violations when they just want to view the info. Not the this PR but do you agree?

File: public/rules/V5RC/2024-2025.json [hunk 7]
```diff
@@ -34,9 +34,16 @@
...
+        {
+          "rule": "<SG6 - Goals>",
```
[the remark this answers is not in the document]
Comment (MiniMitre) [reply public/rules/V5RC/2024-2025.json:43]: Do you think we should we clear out rule history entirely, or just for SG6?

File: src/components/Incident.tsx [hunk 8]
```diff
@@ -28,21 +30,52 @@ export const Incident: React.FC<IncidentProps> = ({
...
-    if (incident.rules.length > 1) {
-      base.push(incident.rules[0] + " + " + (incident.rules.length - 1));
-    } else {
-      base.push(incident.rules[0]);
-    }
+    var validIcon;
+    incident.rules.forEach((rule, count) => {
+      const icon = rules?.ruleGroups
+        .flatMap((ruleGroup) => {
+          const result = ruleGroup.rules.find((r) => r.rule === rule); // Find a matching rule
```
[the remark this answers is not in the document]
Comment (MiniMitre) [reply src/components/Incident.tsx:48]: We want to have the rules split by section for the initial user selection, so I quite like having the rules split into sections in the JSON. Maybe we could pre-process the JSON like this:

```js
const createRuleLookup = rulegroups => {
  const lookup = {};
  rulegroups.forEach(group => {
    group.rules.forEach(rule => {
     lookup[rule.rule] = rule;
    });
  });
  return lookup;
};
const ruleLookup = createRuleLookup(rules.rulegroups);
```

```js
Which can then be access with (ruleLookup["<G1>"]
```

Maybe better to remove the `<>`  but I'm not sure.

Do you like this idea or do you think we should re-format the json instead?

File: public/rules/V5RC/2024-2025.json (hunk 7 above)
[the remark this answers is not in the document]
Comment (brenapp) [reply public/rules/V5RC/2024-2025.json:43]: It's probably OK to just remove SG6, we would just have to write the migration a bit more carefully.

File: src/components/Incident.tsx (hunk 8 above)
[the remark this answers is not in the document]
Comment (brenapp) [reply src/components/Incident.tsx:48]: If we change the structure of the JSON, we would need to keep it around the old version for long enough to allow all clients to update it. The better thing is to probably make getter functions in `utils` that cache things in IndexedDB or something.

File: public/icons/High_Stakes_Goal.png
[the remark this answers is not in the document]
Comment (MiniMitre) [reply public/icons/High_Stakes_Goal.png:1]: For now I have changed the files to be compressed versions that are 6k and 10kb in size, which is better.

Definitely still have a little too much detail for the 'emoji' like use case

**Review by MiniMitre — COMMENTED** [review]
One issue I'm struggling with at the moment is what happens if a user tries to edit an incident which contains an <SG6> violation. What do you think the intended behaviour there should be?

File: src/components/Incident.tsx (hunk 4 above)
Comment (MiniMitre) [reply src/components/Incident.tsx]: Another potential issue with removing overflow-x is that the 'edit' button (which is the only crucial piece of information' is the first thing to be removed on overly long entries / small enough screen sizes.
image
Maybe the edit button should go on the left to make sure this is never an issue?

**Comment by brenapp** [comment]
> One issue I'm struggling with is what happens if a user tries to edit an incident containing an `<SG6>` violation. What do you think the intended behavior should be?

We should not modify the incident without the user doing it manually, but if they edit it, it will appear like the rules multi-select is empty, which is suboptimal.

File: src/components/Incident.tsx (hunk 4 above)
Comment (MiniMitre) [reply src/components/Incident.tsx]: I have moved the edit button to the left instead. I think it looks just as good, and the most important piece of information will never be cut off, even on tiny screens.

**Comment by MiniMitre** [comment]
> > One issue I'm struggling with is what happens if a user tries to edit an incident containing an `<SG6>` violation. What do you think the intended behavior should be?
> 
> We should not modify the incident without the user doing it manually, but if they edit it, it will appear like the rules multi-select is empty, which is suboptimal.

Added a fix for this so the app no longer crashes (and the user can exit out and keep the SG6 as it is) I agree it's not optimal but we should probably be prepared for the removal of rules. It hasn't happened as far as I can remember, but rules can be added mid way through a season. So I would imagine rules can also be removed part way through a season

File: src/components/dialogs/edit.tsx [hunk 9]
```diff
@@ -235,7 +229,9 @@ export const EditIncidentDialog: React.FC<EditIncidentDialogProps> = ({
       <DialogBody>
         <label>
           <p className="mt-4">Team</p>
-          <Input value={incident.team} readOnly className="w-full" />
+          <div className="rounded-md bg-zinc-700 text-zinc-100 text-left px-3 py-2 hover:bg-zinc-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-zinc-500 w-full">
```
Comment (MiniMitre) [inline src/components/dialogs/edit.tsx:232]: @brenapp I noticed we don't allow the user to edit the team in the 'Edit' dialog box, is this intentional? And if so I believe we should use a div instead of a readonly input (as that gives a cursor to edit the team number and the user will not expect it to be readonly).

I might be wrong about that though

Comment (brenapp) [reply src/components/dialogs/edit.tsx:232]: Correct - you cannot change the event, division, or team for an incident after it has been created. This is an artifact of the fact that we index these values manually and I didn't want to write indexing logic :)

The whole question about disabled vs read-only inputs vs just text is an interesting one. When it comes to inputs, disabled removes the input from the tab stop order, and should be used when something the user has done on the page prevents them from editing. Read-only should be used when the field cannot be edited for something out of their control, but you still want them to be able to read the value. I kept it as a read-only input cuz that seemed more visually cohesive, but in this case I think it makes sense for it to be some styled text

Comment (MiniMitre) [reply src/components/dialogs/edit.tsx:232]: That makes sense. I noticed it as part of testing my changes to the summary page and thought it was a bug I created. Then I realised it was the same on the live website. Do you think maybe some different type of styling should be used so that the user knows it is intended to not be editable. E.g. text in bold

Comment (MiniMitre) [reply src/components/dialogs/edit.tsx:232]: I'm thinking something like this might work
image

File: src/components/Incident.tsx [hunk 10]
```diff
@@ -21,29 +23,56 @@ export type IncidentProps = {
...
+  return (
+    <>
+      <span key={`${incident.id}-name`}>{incident.team}</span>
+      {"•"}
+      <span key={`${incident.id}-match`}>
+        {incident.match ? matchToString(incident.match) : "Non-Match"}
+      </span>
+      {"•"}
+      <span>
+        {incident.rules.length >= 2 ? (
```
Comment (brenapp) [inline src/components/Incident.tsx]: I think the `<SG6> + 1` style here is best in the situation where we have multiple rules

Comment (brenapp) [reply src/components/Incident.tsx]: See 0fe95c637c8d3ea71396e76ee593906f729b1ff2

**Review by brenapp — CHANGES_REQUESTED** [review]

File: src/components/Incident.tsx [hunk 11]
```diff
@@ -56,12 +85,25 @@ export const Incident: React.FC<IncidentProps> = ({
         {...props}
         className={twMerge(
           IncidentOutcomeClasses[incident.outcome],
-          "px-4 py-2 rounded-md mt-2 flex",
+          "pr-4 py-2 rounded-md mt-2 flex",
           props.className
         )}
       >
+        {!readonly ? (
```
Comment (brenapp) [inline src/components/Incident.tsx:89]: Ok, so I know that we originally changed the edit button to be on the left because it helped to ensure it did not become invisible if we overflowed, but since that is not an issue, I think we should move it back. Most people are right handed, and placing it on the left means more people would have to reach on their larger devices to keep it, and the product becomes less one-hand friendly.

**Review by brenapp — CHANGES_REQUESTED** [review]

File: src/components/Incident.tsx (hunk 11 above)
Comment (brenapp) [reply src/components/Incident.tsx]: [75db352](https://github.com/brenapp/referee.fyi/pull/165/commits/75db35208cf869ffe4cff78385e4bdc18b28387e)

File: src/components/dialogs/edit.tsx [hunk 12]
```diff
@@ -2,13 +2,7 @@ import React, { useCallback, useEffect, useMemo, useState } from "react";
...
 import { Button } from "~components/Button";
 import { Dialog, DialogBody, DialogHeader } from "~components/Dialog";
-import {
-  Input,
-  Radio,
-  RulesMultiSelect,
-  Select,
-  TextArea,
-} from "~components/Input";
+import { Radio, RulesMultiSelect, Select, TextArea } from "~components/Input";
```
Comment (brenapp) [inline src/components/dialogs/edit.tsx:5]: When editing an existing rule, I am still getting this fatal error encountered.

image

The stack trace points to 

```ts
// Input.tsx

      const rule = game?.ruleGroups
        .find((g) => g.name === group)
        ?.rules.find((r) => r.rule === e.target.value);

```

Comment (brenapp) [reply src/components/dialogs/edit.tsx:5]: This is the logic in `RulesMultiSelect`

Comment (brenapp) [reply src/components/dialogs/edit.tsx:5]: The `rules` list here is being passed as an array of `undefined`

From `EditIncidentDialog`

```tsx
  const enrichRules = useCallback(
    (rules: string[]) => {
      const gameRules = game?.ruleGroups.flatMap((group) => group.rules) ?? [];
      return rules.map((rule) => gameRules.find((r) => r.rule === rule)!);
    },
    [game]
  );

  const initialRichRules = useMemo(() => {
    return enrichRules(incident.rules);
  }, [enrichRules, incident.rules]);
```

Comment (brenapp) [reply src/components/dialogs/edit.tsx:5]: This was an incident with a `<SG6>` rule saved

Comment (brenapp) [reply src/components/dialogs/edit.tsx:5]: See 25039e1faf534faed27c9a4f7cf48b58ea8cb488. Now we filter out rules we cannot find when enriching them in the incident edit dialog. I think this behavior is fine, since we do not expect people to edit incidents after the event ends. We should make sure to deploy this change either Tuesday or Wednesday to prevent interference with any upcoming events.

File: src/components/dialogs/edit.tsx [hunk 13]
```diff
@@ -235,7 +229,9 @@ export const EditIncidentDialog: React.FC<EditIncidentDialogProps> = ({
       <DialogBody>
         <label>
           <p className="mt-4">Team</p>
-          <Input value={incident.team} readOnly className="w-full" />
+          <div className="rounded-md bg-zinc-700 text-zinc-100 text-left px-3 py-2 w-fit font-semibold">
```
Comment (brenapp) [inline src/components/dialogs/edit.tsx]: If the team is not editable, and we want to make it text, let's do it, let's not style it to look like an input.

Comment (brenapp) [reply src/components/dialogs/edit.tsx]: What do you think of c3b93f2f4785a7fedaff33b56121aa4ae88fdb4d?

**Review by brenapp — CHANGES_REQUESTED** [review]

File: public/rules/V5RC/2024-2025.json [hunk 14]
```diff
@@ -34,9 +34,16 @@
           "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/SG5.html"
         },
         {
-          "rule": "<SG6>",
-          "description": "Possession is limited to two Rings and one Mobile Goal",
-          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/SG6.html"
+          "rule": "<SG6-R>",
+          "description": "Possession is limited to two Rings",
+          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/SG6.html",
+          "icon": "/rules/V5RC/2024-2025/icons/High_Stakes_Ring.svg"
```
Comment (brenapp) [inline public/rules/V5RC/2024-2025.json:40]: I think the icons are flipped

File: src/components/dialogs/edit.tsx (hunk 12 above)
Comment (MiniMitre) [reply src/components/dialogs/edit.tsx:5]: I made the same change to input.tsx as it fixed the issue for me. Do you think this is still needed?

5405307c3d62c287fbaa1189dd9f6315102b813e

File: src/components/Incident.tsx (hunk 11 above)
Comment (MiniMitre) [reply src/components/Incident.tsx]: Yeah after testing i actually agree, it was annoying to have it on the left.

File: public/rules/V5RC/2024-2025.json (hunk 14 above)
Comment (MiniMitre) [reply public/rules/V5RC/2024-2025.json:40]: This was fixed in 0320aad58a8ef02a344326fa9ddc6b3969b278dd.

If you added the rules before that update, the 'associated rules' will remain incorrect.

I still have <SG6 - Rings> Icon from some of the older changes
image
Shouldn't be a problem for users

**Review by MiniMitre — COMMENTED** [review]
The reason I went for 'X vios' instead of 'first vio + X-1' was because, with the addition of the icon for `<SG6>`, we are over the screen size limit of smaller devices. Image shown is my phone (folded) at 369px, but we really should be making sure it works on 320px (the generally accepted minimum size of a device)

image

However, now I think we should put the edit button absolutely over the top of the incident, and have the other information clip under it. That way we can have the edit button on the right and never dissapearing
Thoughts?

**Comment by brenapp** [comment]
> The reason I went for 'X vios' instead of 'first vio + X-1' was because, with the addition of the icon for `<SG6>`, we are over the screen size limit of smaller devices. Image shown is my phone (folded) at 369px, but we really should be making sure it works on 320px (the generally accepted minimum size of a device)
> 
> image
> 
> However, now I think we should put the edit button absolutely over the top of the incident, and have the other information clip under it. That way we can have the edit button on the right and never dissapearing
> Thoughts?

That only hides minor, but that should be clear from the color, so I am good!

File: src/components/dialogs/edit.tsx (hunk 13 above)
Comment (MiniMitre) [reply src/components/dialogs/edit.tsx]: I agree it shouldn't look like an input. I don't like the small text and think the default size, the same as the other input fields, fits better with the rest of the edit page.

Added in 345513d9a9857a84815b523a242b17910da826be

**Comment by MiniMitre** [comment]
I agree we want to push this update at a time when no V5 events are currently ongoing. I don't think IQ events will be affected but we wouldn't want to push in the middle of an IQ sig (just in case)

File: src/components/Input.tsx [hunk 15]
```diff
@@ -358,22 +358,33 @@ export const RulesMultiSelect: React.FC<RulesMultiSelectProps> = ({
...
+                      src={rule.icon}
+                      alt={`Icon`}
+                      className="max-h-6 w-auto"
+                    />
+                  )}
+                </div>
+                <span>{rule.description}</span>
+              </div>
+              <IconButton
+                className="bg-transparent"
```
Comment (brenapp) [inline src/components/Input.tsx:382]: In the match dialog, the edit button is rendering wacky here

image

Comment (brenapp) [reply src/components/Input.tsx:382]: Fixed in e89cf53b62d8325628556310eb9c0e7f2e76a29a

**Review by brenapp — APPROVED** [review]
